/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  Livraison as PrismaLivraison,
  Client as PrismaClient,
} from "@prisma/client";

export class LivraisonServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.LivraisonCountArgs, "select">
  ): Promise<number> {
    return this.prisma.livraison.count(args);
  }

  async livraisons(
    args: Prisma.LivraisonFindManyArgs
  ): Promise<PrismaLivraison[]> {
    return this.prisma.livraison.findMany(args);
  }
  async livraison(
    args: Prisma.LivraisonFindUniqueArgs
  ): Promise<PrismaLivraison | null> {
    return this.prisma.livraison.findUnique(args);
  }
  async createLivraison(
    args: Prisma.LivraisonCreateArgs
  ): Promise<PrismaLivraison> {
    return this.prisma.livraison.create(args);
  }
  async updateLivraison(
    args: Prisma.LivraisonUpdateArgs
  ): Promise<PrismaLivraison> {
    return this.prisma.livraison.update(args);
  }
  async deleteLivraison(
    args: Prisma.LivraisonDeleteArgs
  ): Promise<PrismaLivraison> {
    return this.prisma.livraison.delete(args);
  }

  async getClient(parentId: string): Promise<PrismaClient | null> {
    return this.prisma.livraison
      .findUnique({
        where: { id: parentId },
      })
      .client();
  }
}
