/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Livraison } from "./Livraison";
import { LivraisonCountArgs } from "./LivraisonCountArgs";
import { LivraisonFindManyArgs } from "./LivraisonFindManyArgs";
import { LivraisonFindUniqueArgs } from "./LivraisonFindUniqueArgs";
import { CreateLivraisonArgs } from "./CreateLivraisonArgs";
import { UpdateLivraisonArgs } from "./UpdateLivraisonArgs";
import { DeleteLivraisonArgs } from "./DeleteLivraisonArgs";
import { Client } from "../../client/base/Client";
import { LivraisonService } from "../livraison.service";
@graphql.Resolver(() => Livraison)
export class LivraisonResolverBase {
  constructor(protected readonly service: LivraisonService) {}

  async _livraisonsMeta(
    @graphql.Args() args: LivraisonCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Livraison])
  async livraisons(
    @graphql.Args() args: LivraisonFindManyArgs
  ): Promise<Livraison[]> {
    return this.service.livraisons(args);
  }

  @graphql.Query(() => Livraison, { nullable: true })
  async livraison(
    @graphql.Args() args: LivraisonFindUniqueArgs
  ): Promise<Livraison | null> {
    const result = await this.service.livraison(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Livraison)
  async createLivraison(
    @graphql.Args() args: CreateLivraisonArgs
  ): Promise<Livraison> {
    return await this.service.createLivraison({
      ...args,
      data: {
        ...args.data,

        client: args.data.client
          ? {
              connect: args.data.client,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Livraison)
  async updateLivraison(
    @graphql.Args() args: UpdateLivraisonArgs
  ): Promise<Livraison | null> {
    try {
      return await this.service.updateLivraison({
        ...args,
        data: {
          ...args.data,

          client: args.data.client
            ? {
                connect: args.data.client,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Livraison)
  async deleteLivraison(
    @graphql.Args() args: DeleteLivraisonArgs
  ): Promise<Livraison | null> {
    try {
      return await this.service.deleteLivraison(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Client, {
    nullable: true,
    name: "client",
  })
  async getClient(@graphql.Parent() parent: Livraison): Promise<Client | null> {
    const result = await this.service.getClient(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
