/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { LivraisonService } from "../livraison.service";
import { LivraisonCreateInput } from "./LivraisonCreateInput";
import { Livraison } from "./Livraison";
import { LivraisonFindManyArgs } from "./LivraisonFindManyArgs";
import { LivraisonWhereUniqueInput } from "./LivraisonWhereUniqueInput";
import { LivraisonUpdateInput } from "./LivraisonUpdateInput";

export class LivraisonControllerBase {
  constructor(protected readonly service: LivraisonService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Livraison })
  async createLivraison(
    @common.Body() data: LivraisonCreateInput
  ): Promise<Livraison> {
    return await this.service.createLivraison({
      data: {
        ...data,

        client: data.client
          ? {
              connect: data.client,
            }
          : undefined,
      },
      select: {
        client: {
          select: {
            id: true,
          },
        },

        convertiEnFacture: true,
        createdAt: true,
        date: true,
        id: true,
        ligneProduits: true,
        numero: true,
        total: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Livraison] })
  @ApiNestedQuery(LivraisonFindManyArgs)
  async livraisons(@common.Req() request: Request): Promise<Livraison[]> {
    const args = plainToClass(LivraisonFindManyArgs, request.query);
    return this.service.livraisons({
      ...args,
      select: {
        client: {
          select: {
            id: true,
          },
        },

        convertiEnFacture: true,
        createdAt: true,
        date: true,
        id: true,
        ligneProduits: true,
        numero: true,
        total: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Livraison })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async livraison(
    @common.Param() params: LivraisonWhereUniqueInput
  ): Promise<Livraison | null> {
    const result = await this.service.livraison({
      where: params,
      select: {
        client: {
          select: {
            id: true,
          },
        },

        convertiEnFacture: true,
        createdAt: true,
        date: true,
        id: true,
        ligneProduits: true,
        numero: true,
        total: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Livraison })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateLivraison(
    @common.Param() params: LivraisonWhereUniqueInput,
    @common.Body() data: LivraisonUpdateInput
  ): Promise<Livraison | null> {
    try {
      return await this.service.updateLivraison({
        where: params,
        data: {
          ...data,

          client: data.client
            ? {
                connect: data.client,
              }
            : undefined,
        },
        select: {
          client: {
            select: {
              id: true,
            },
          },

          convertiEnFacture: true,
          createdAt: true,
          date: true,
          id: true,
          ligneProduits: true,
          numero: true,
          total: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Livraison })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteLivraison(
    @common.Param() params: LivraisonWhereUniqueInput
  ): Promise<Livraison | null> {
    try {
      return await this.service.deleteLivraison({
        where: params,
        select: {
          client: {
            select: {
              id: true,
            },
          },

          convertiEnFacture: true,
          createdAt: true,
          date: true,
          id: true,
          ligneProduits: true,
          numero: true,
          total: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
