/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Facture } from "./Facture";
import { FactureCountArgs } from "./FactureCountArgs";
import { FactureFindManyArgs } from "./FactureFindManyArgs";
import { FactureFindUniqueArgs } from "./FactureFindUniqueArgs";
import { CreateFactureArgs } from "./CreateFactureArgs";
import { UpdateFactureArgs } from "./UpdateFactureArgs";
import { DeleteFactureArgs } from "./DeleteFactureArgs";
import { Client } from "../../client/base/Client";
import { FactureService } from "../facture.service";
@graphql.Resolver(() => Facture)
export class FactureResolverBase {
  constructor(protected readonly service: FactureService) {}

  async _facturesMeta(
    @graphql.Args() args: FactureCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Facture])
  async factures(
    @graphql.Args() args: FactureFindManyArgs
  ): Promise<Facture[]> {
    return this.service.factures(args);
  }

  @graphql.Query(() => Facture, { nullable: true })
  async facture(
    @graphql.Args() args: FactureFindUniqueArgs
  ): Promise<Facture | null> {
    const result = await this.service.facture(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Facture)
  async createFacture(
    @graphql.Args() args: CreateFactureArgs
  ): Promise<Facture> {
    return await this.service.createFacture({
      ...args,
      data: {
        ...args.data,

        client: args.data.client
          ? {
              connect: args.data.client,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Facture)
  async updateFacture(
    @graphql.Args() args: UpdateFactureArgs
  ): Promise<Facture | null> {
    try {
      return await this.service.updateFacture({
        ...args,
        data: {
          ...args.data,

          client: args.data.client
            ? {
                connect: args.data.client,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Facture)
  async deleteFacture(
    @graphql.Args() args: DeleteFactureArgs
  ): Promise<Facture | null> {
    try {
      return await this.service.deleteFacture(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Client, {
    nullable: true,
    name: "client",
  })
  async getClient(@graphql.Parent() parent: Facture): Promise<Client | null> {
    const result = await this.service.getClient(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
